export interface ApiErrorBody {
  statusCode: number;
  code: string;
  message: string;
  requestId?: string;
  details?: unknown;
}

export const ERROR_CODES = {
  VALIDATION_FAILED: 'Os dados informados são inválidos.',
  AUTH_INVALID_CREDENTIALS: 'E-mail ou senha incorretos.',
  AUTH_USER_INACTIVE: 'Este usuário está inativo ou bloqueado.',
  AUTH_TOKEN_INVALID: 'Sessão inválida ou expirada.',
  AUTH_REFRESH_INVALID: 'Sessão expirada. Faça login novamente.',
  AUTH_RESET_INVALID: 'O link de redefinição é inválido ou expirou.',
  AUTH_FORBIDDEN: 'Você não tem permissão para esta ação.',
  AUTH_WEAK_PASSWORD: 'A senha deve ter ao menos 10 caracteres, com letras e números.',
  RATE_LIMITED: 'Muitas tentativas. Aguarde um instante e tente novamente.',
  NOT_FOUND: 'Registro não encontrado.',
  USER_EMAIL_TAKEN: 'Já existe um usuário com este e-mail.',
  USER_SELF_DELETE: 'Você não pode excluir o seu próprio usuário.',
  USER_ROLE_INVALID: 'O papel informado não existe.',
  BRANCH_INVALID: 'A filial informada não existe.',
  PROPERTY_INVALID_PRICE: 'O valor informado para o imóvel é inválido.',
  PROPERTY_INCOMPLETE: 'Complete os dados obrigatórios antes de publicar o imóvel.',
  PROPERTY_NOT_DELETABLE: 'Só é possível excluir imóveis em rascunho. Use "Arquivar" para os demais.',
  PROPERTY_STATUS_INVALID: 'Use a ação "Arquivar" para arquivar o imóvel.',
  PROPERTY_TYPE_INVALID: 'O tipo de imóvel informado não existe.',
  OWNER_INVALID: 'O proprietário informado não existe.',
  OWNER_HAS_PROPERTIES: 'Este proprietário possui imóveis vinculados e não pode ser excluído.',
  BROKER_INVALID: 'O corretor informado não existe ou está inativo.',
  FEATURE_INVALID: 'Uma ou mais características informadas não existem.',
  CATALOG_NAME_TAKEN: 'Já existe um item com este nome.',
  MEDIA_TYPE_INVALID: 'Tipo de arquivo não permitido para esta mídia.',
  MEDIA_TOO_LARGE: 'O arquivo excede o tamanho máximo permitido.',
  MEDIA_NOT_UPLOADED: 'O arquivo não foi encontrado no armazenamento. Tente enviar novamente.',
  MEDIA_KEY_INVALID: 'Referência de arquivo inválida.',
  MEDIA_LIMIT_REACHED: 'Este imóvel atingiu o limite de mídias.',
  MEDIA_NOT_IMAGE: 'Somente fotos podem ser definidas como capa.',
  MEDIA_ORDER_INVALID: 'A ordem informada não corresponde às mídias do imóvel.',
  MEDIA_NOT_FAILED: 'Somente mídias com falha podem ser reprocessadas.',
  STORAGE_UPLOAD_INVALID: 'Envio inválido ou expirado.',
  LEAD_PROPERTY_INVALID: 'O imóvel informado não está mais disponível.',
  PROPERTY_INVALID: 'O imóvel informado não existe.',
  LEAD_LOST_REASON_REQUIRED: 'Informe o motivo da perda do lead.',
  LEAD_STAGE_INVALID: 'O estágio informado não existe.',
  LEAD_CUSTOMER_INVALID: 'O cliente informado não existe.',
  LEAD_BROKER_INVALID: 'O corretor informado não existe ou está inativo.',
  LEAD_NO_BROKER_AVAILABLE: 'Não há corretores ativos para receber o lead.',
  TASK_INVALID: 'A tarefa informada não existe ou já foi concluída.',
  SOCIAL_NOT_CONFIGURED: 'O login com o Facebook ainda não foi configurado neste sistema (META_APP_ID e META_APP_SECRET).',
  SOCIAL_ACCOUNT_INVALID: 'Uma ou mais contas escolhidas não estão conectadas.',
  SOCIAL_MEDIA_INVALID: 'Uma ou mais fotos não pertencem a este imóvel ou ainda estão em processamento.',
  SOCIAL_INSTAGRAM_CAPTION: 'O Instagram aceita até 2.200 caracteres no texto.',
  SOCIAL_SCHEDULE_INVALID: 'Escolha uma data futura (até 180 dias).',
  SOCIAL_POST_LOCKED: 'Esta publicação não pode mais ser alterada.',
  SOCIAL_TARGET_NOT_RETRYABLE: 'Só é possível reenviar destinos que falharam.',
  META_NOT_CONFIGURED: 'A Meta (Pixel e Conversions API) ainda não foi conectada. Configure em Integrações.',
  META_TEST_FAILED: 'A Meta recusou o evento de teste.',
  MARKETING_EVENT_NOT_RETRYABLE: 'Só eventos que falharam podem ser reenviados.',
  WEBHOOK_SIGNATURE_INVALID: 'Assinatura do webhook inválida.',
  WHATSAPP_NOT_CONFIGURED: 'O WhatsApp ainda não foi conectado. Configure em Integrações.',
  WHATSAPP_WINDOW_CLOSED: 'Passaram mais de 24 horas desde a última mensagem do cliente. Envie um modelo de mensagem aprovado.',
  WHATSAPP_SEND_FAILED: 'Não foi possível enviar a mensagem pelo WhatsApp.',
  WHATSAPP_PHONE_IN_USE: 'Este número do WhatsApp já está conectado a outra empresa.',
  WHATSAPP_TEST_FAILED: 'Não foi possível validar as credenciais com a Meta.',
  WHATSAPP_MEDIA_UNAVAILABLE: 'Não foi possível baixar o arquivo desta mensagem.',
  MESSAGE_NOT_RETRYABLE: 'Somente mensagens enviadas que falharam podem ser reenviadas.',
  INTERNAL_ERROR: 'Ocorreu um erro inesperado. Tente novamente.',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
