export interface ApiErrorBody {
  statusCode: number;
  code: string;
  message: string;
  requestId?: string;
  details?: unknown;
}

export const ERROR_CODES = {
  VALIDATION_FAILED: 'Os dados informados são inválidos.',
  AUTH_INVALID_CREDENTIALS: 'E-mail ou senha incorretos.',
  AUTH_USER_INACTIVE: 'Este usuário está inativo ou bloqueado.',
  AUTH_TOKEN_INVALID: 'Sessão inválida ou expirada.',
  AUTH_REFRESH_INVALID: 'Sessão expirada. Faça login novamente.',
  AUTH_RESET_INVALID: 'O link de redefinição é inválido ou expirou.',
  AUTH_FORBIDDEN: 'Você não tem permissão para esta ação.',
  AUTH_WEAK_PASSWORD: 'A senha deve ter ao menos 10 caracteres, com letras e números.',
  RATE_LIMITED: 'Muitas tentativas. Aguarde um instante e tente novamente.',
  NOT_FOUND: 'Registro não encontrado.',
  USER_EMAIL_TAKEN: 'Já existe um usuário com este e-mail.',
  USER_SELF_DELETE: 'Você não pode excluir o seu próprio usuário.',
  USER_ROLE_INVALID: 'O papel informado não existe.',
  BRANCH_INVALID: 'A filial informada não existe.',
  PROPERTY_INVALID_PRICE: 'O valor informado para o imóvel é inválido.',
  PROPERTY_INCOMPLETE: 'Complete os dados obrigatórios antes de publicar o imóvel.',
  PROPERTY_NOT_DELETABLE: 'Só é possível excluir imóveis em rascunho. Use "Arquivar" para os demais.',
  PROPERTY_STATUS_INVALID: 'Use a ação "Arquivar" para arquivar o imóvel.',
  PROPERTY_TYPE_INVALID: 'O tipo de imóvel informado não existe.',
  OWNER_INVALID: 'O proprietário informado não existe.',
  OWNER_HAS_PROPERTIES: 'Este proprietário possui imóveis vinculados e não pode ser excluído.',
  BROKER_INVALID: 'O corretor informado não existe ou está inativo.',
  FEATURE_INVALID: 'Uma ou mais características informadas não existem.',
  CATALOG_NAME_TAKEN: 'Já existe um item com este nome.',
  MEDIA_TYPE_INVALID: 'Tipo de arquivo não permitido para esta mídia.',
  MEDIA_TOO_LARGE: 'O arquivo excede o tamanho máximo permitido.',
  MEDIA_NOT_UPLOADED: 'O arquivo não foi encontrado no armazenamento. Tente enviar novamente.',
  MEDIA_KEY_INVALID: 'Referência de arquivo inválida.',
  MEDIA_LIMIT_REACHED: 'Este imóvel atingiu o limite de mídias.',
  MEDIA_NOT_IMAGE: 'Somente fotos podem ser definidas como capa.',
  MEDIA_ORDER_INVALID: 'A ordem informada não corresponde às mídias do imóvel.',
  MEDIA_NOT_FAILED: 'Somente mídias com falha podem ser reprocessadas.',
  STORAGE_UPLOAD_INVALID: 'Envio inválido ou expirado.',
  LEAD_PROPERTY_INVALID: 'O imóvel informado não está mais disponível.',
  PROPERTY_INVALID: 'O imóvel informado não existe.',
  LEAD_LOST_REASON_REQUIRED: 'Informe o motivo da perda do lead.',
  LEAD_STAGE_INVALID: 'O estágio informado não existe.',
  LEAD_CUSTOMER_INVALID: 'O cliente informado não existe.',
  LEAD_BROKER_INVALID: 'O corretor informado não existe ou está inativo.',
  LEAD_NO_BROKER_AVAILABLE: 'Não há corretores ativos para receber o lead.',
  TASK_INVALID: 'A tarefa informada não existe ou já foi concluída.',
  VISIT_CONFLICT: 'O corretor já tem uma visita neste horário.',
  VISIT_STATUS_INVALID: 'Esta visita não pode mais ser alterada dessa forma.',
  VISIT_PROPERTY_UNAVAILABLE: 'Este imóvel não está mais disponível para visitas.',
  PROPOSAL_PROPERTY_UNAVAILABLE: 'Este imóvel não está mais disponível para propostas.',
  VISIT_PAST: 'A data da visita não pode estar no passado.',
  VISIT_PROPERTY_REQUIRED: 'Informe o imóvel da visita.',
  PROPOSAL_STATUS_INVALID: 'Não é possível mudar a proposta para este status.',
  PROPOSAL_CLOSED: 'Esta proposta já foi encerrada e não pode mais ser alterada.',
  PROPOSAL_NOT_ACCEPTED: 'Só uma proposta aceita pode ser fechada como negócio.',
  PROPOSAL_PROPERTY_REQUIRED: 'Informe o imóvel da proposta.',
  PROPOSAL_PRICE_INVALID: 'O valor da proposta é inválido.',
  SOCIAL_NOT_CONFIGURED: 'Cadastre o ID e a chave secreta do aplicativo da Meta antes de entrar com o Facebook.',
  AI_OPERATION_UNSUPPORTED: 'Esta edição precisa de um provedor de IA. Configure o Google Gemini ou a OpenAI em Empresa → Imagens e IA.',
  AI_PROMPT_REQUIRED: 'Descreva o que deve ser removido.',
  AI_LIMIT_REACHED: 'O limite mensal de edições por IA da empresa foi atingido.',
  AI_KEY_INVALID: 'O provedor de IA não aceitou a chave informada.',
  AI_MEDIA_INVALID: 'Só fotos já processadas podem ser editadas por IA.',
  AI_GENERATION_BUSY: 'Esta foto já tem uma edição em andamento. Aguarde terminar.',
  AI_GENERATION_NOT_READY: 'Só uma versão pronta pode ser aprovada.',
  AI_GENERATION_IN_USE: 'Esta versão está publicada ou serviu de base para outra e não pode ser descartada.',
  LOGO_INVALID: 'Não foi possível ler a logo. Envie PNG, JPG, WebP ou SVG com pelo menos 64 px.',
  LOGO_REQUIRED: 'Envie a logo antes de ativar a marca d’água.',
  SOCIAL_FORBIDDEN: 'Só quem cadastrou pode alterar isto.',
  SOCIAL_APP_REQUIRED: 'Escolha qual aplicativo da Meta usar para entrar.',
  SOCIAL_APP_DUPLICATE: 'Este aplicativo (ID) já está cadastrado.',
  SOCIAL_APP_INVALID: 'A Meta não aceitou o ID do app ou a chave secreta. Confira os dados no painel de desenvolvedores.',
  SOCIAL_ACCOUNT_INVALID: 'Uma ou mais contas escolhidas não estão conectadas.',
  SOCIAL_MEDIA_INVALID: 'Uma ou mais fotos não pertencem a este imóvel ou ainda estão em processamento.',
  SOCIAL_INSTAGRAM_CAPTION: 'O Instagram aceita até 2.200 caracteres no texto.',
  SOCIAL_SCHEDULE_INVALID: 'Escolha uma data futura (até 180 dias).',
  SOCIAL_POST_LOCKED: 'Esta publicação não pode mais ser alterada.',
  SOCIAL_TARGET_NOT_RETRYABLE: 'Só é possível reenviar destinos que falharam.',
  META_NOT_CONFIGURED: 'A Meta (Pixel e Conversions API) ainda não foi conectada. Configure em Integrações.',
  META_TEST_FAILED: 'A Meta recusou o evento de teste.',
  MARKETING_EVENT_NOT_RETRYABLE: 'Só eventos que falharam podem ser reenviados.',
  WEBHOOK_SIGNATURE_INVALID: 'Assinatura do webhook inválida.',
  WHATSAPP_NOT_CONFIGURED: 'O WhatsApp ainda não foi conectado. Configure em Integrações.',
  WHATSAPP_WINDOW_CLOSED: 'Passaram mais de 24 horas desde a última mensagem do cliente. Envie um modelo de mensagem aprovado.',
  WHATSAPP_SEND_FAILED: 'Não foi possível enviar a mensagem pelo WhatsApp.',
  WHATSAPP_PHONE_IN_USE: 'Este número do WhatsApp já está conectado a outra empresa.',
  WHATSAPP_TEST_FAILED: 'Não foi possível validar as credenciais com a Meta.',
  WHATSAPP_MEDIA_UNAVAILABLE: 'Não foi possível baixar o arquivo desta mensagem.',
  MESSAGE_NOT_RETRYABLE: 'Somente mensagens enviadas que falharam podem ser reenviadas.',
  INTERNAL_ERROR: 'Ocorreu um erro inesperado. Tente novamente.',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
